### PR TITLE
z3 package is case-sensitible at Linux

### PR DESCRIPTION
**Pull request by master-q**

### CODE REVIEW

**Comment by rafoo** [comment]
Hello, I am responsible for the capitalization, I did it precisely because I had the opposite problem on my linux machine (see pull request #87). What is your version of Z3 and how do you install it?

**Comment by master-q** [comment]
I installed the Z3-4.6 with opam. Please see https://github.com/verifast/verifast/issues/115#issuecomment-358612865 .
Do you means that if I install Z3 using following method, I will find it with `Z3`?

https://github.com/verifast/verifast/blob/master/README.Z3v4.5.md

**Comment by btj** [comment]
See https://github.com/verifast/verifast/commit/4f8769d8b2ef55e4fc82d8a035108cb3fd0f73fb

**Comment by btj** [comment]
https://github.com/verifast/verifast/commit/4f8769d8b2ef55e4fc82d8a035108cb3fd0f73fb was buggy; fixed version is https://github.com/verifast/verifast/commit/550e4ee834ad6a18517e8934036871a78adca570

**Comment by master-q** [comment]
Umm... I understand there are many issues on z3 package.
I'll try there solution.

**Pull request closed without merging**
